// API Requests
export const REQUESTS_BEGIN = 'REQUESTS_BEGIN'
export const REQUESTS_END = 'REQUESTS_END'
export const REQUESTS_ERROR = 'REQUESTS_ERROR'
export const REQUESTS_CLEAR = 'REQUESTS_CLEAR'

// Auth
export const UPDATE_OFFLINE_SWITCH = 'UPDATE_OFFLINE_SWITCH'
export const UPDATE_CURRENT_USER = 'UPDATE_CURRENT_USER'
export const UPDATE_AUTH_STATE = 'UPDATE_AUTH_STATE'
export const REFRESH_AUTH = 'REFRESH_AUTH'
export const FORCE_LOGIN = 'FORCE_LOGIN'

// Projects
export const UPDATE_PROJECTS = 'UPDATE_PROJECTS'
export const GET_LOCAL_INSPECTIONS = 'GET_LOCAL_INSPECTIONS'

export const UPDATE_ITEMS = 'UPDATE_ITEMS'

export const UPDATE_INSPECTION = 'UPDATE_INSPECTION'
export const UPDATE_INSPECTIONS = 'UPDATE_INSPECTIONS'
export const DELETE_INSPECTION = 'DELETE_INSPECTION'
export const CURRENT_INSPECTION = 'CURRENT_INSPECTION'
